### ISSUE TITLE
api

### ISSUE THREAD

**Issue by kamal-F** [anonmanis/AplikasiProyek3-Irvan#33]
untuk firebase api sudah di test, get,post? kalau yg nodemcu sudah buat repo nya?

**Comment by anonmanis** [comment]
untuk yang method post sudah pak, method get untuk notif lampu led di nodemcu  jika tapping berhasil atau gagal, masih ada error pak.
repo nodemcu sudah ada pak, tapi belum saya pull. nanti akan saya pull pak.
