### ISSUE TITLE
upload skema

### ISSUE THREAD

**Issue by kamal-F** [anonmanis/AplikasiProyek3-Irvan#44]
coba lihat skemanya, jika sudah dibuat, ber saja link nya

**Comment by anonmanis** [comment]
https://github.com/anonmanis/RFID-NodeMCUV3-Firebase/blob/master/Skema%20NodeMCU%2BRFID.png

ini untuk link skema NodeMCU + RFID pak, skema sudah saya push di repo RFID-NodeMCUV3-Firebase https://github.com/anonmanis/RFID-NodeMCUV3-Firebase

terima kasih pak

**Comment by Dikasukmap** [comment]
https://github.com/anonmanis/RFID-NodeMCUV3-Firebase/blob/master/Skema%20NodeMCU%2BRFID.png

skemanya sudah di upload pada link diatas pak
